### ISSUE TITLE
Problems of loading opus library

### ISSUE THREAD

**Issue by CyberRex0** [TeamPyOgg/PyOgg#97]
There seems to be a problem with library_loader.py, which loads the Opus library.

In lines 104 to 105 of [library_loader.py](https://github.com/TeamPyOgg/PyOgg/blob/6871a4f234e8a3a346c4874a12509bfa02c4c63a/pyogg/library_loader.py#L104-L105), it seems that a path is added to expand the library search range, but this prevents the globally installed Opus library from being loaded in some environments.

This is the REPL when we confirmed that the process of extending the search range was causing the problem:
```
>>> import ctypes.util
>>> ctypes.util.find_library('opus')
'libopus.so'
>>> import pyogg
>>> pyogg.OpusEncoder()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/pyogg/__init__.py", line 74, in __init__
    raise PyOggError("The Opus library wasn't found or couldn't be loaded (maybe you're trying to use 64bit libraries with 32bit Python?)")
pyogg.pyogg_error.PyOggError: The Opus library wasn't found or couldn't be loaded (maybe you're trying to use 64bit libraries with 32bit Python?)
>>> ctypes.util.find_library('opus')
>>>
```

Commenting out lines 104 and 105 eliminated this problem.

# Additional Information
- Termux on Android 11
- libopus installed
- libopusfile installed
- libopusenc installed
- PyOgg 0.7 (using latest github commit)
- Python 3.10

**Comment by spearman** [comment]
Why is semicolon used as a separator on lines 104, 105? It seems to break PATH so subprocess.Popen can't find anything.
